<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

class AnggotaSeeder extends Seeder
{
    public function run(): void
    {
        $anggotas = [
            //admin
            [
                'roleID' => 1, 
                'username' => 'evan01',
                'nama' => 'Amadeus',
                'DoB' => '2003-02-25',
                'TelpNo' => '081234567890',
                'ortu_nama' => 'Fx',
                'ortu_telp_no' => '087654321098',
                'tanggal_bergabung' => Carbon::now(),
                'status_anggota' => true,
                'password' => Hash::make('123456'),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            //pengurus
            [
                'roleID' => 3, 
                'username' => 'StevanB',
                'nama' => 'Stevan Beale',
                'DoB' => '2003-02-25',
                'TelpNo' => '081234567890',
                'ortu_nama' => 'Fx',
                'ortu_telp_no' => '087654321098',
                'tanggal_bergabung' => Carbon::now(),
                'status_anggota' => true,
                'password' => Hash::make('123456'),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'roleID' => 3, 
                'username' => 'Vincent01',
                'nama' => 'Vincent',
                'DoB' => '2005-02-17',
                'TelpNo' => '573862',
                'ortu_nama' => 'Om Lukman',
                'ortu_telp_no' => '2545467',
                'tanggal_bergabung' => Carbon::now(),
                'status_anggota' => true,
                'password' => Hash::make('123456'),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            

            //PiMi 1
            [
                'roleID' => 4, 
                'username' => 'Jonny01',
                'nama' => 'Jonny',
                'DoB' => '1967-02-17',
                'TelpNo' => '7863453',
                'ortu_nama' => '',
                'ortu_telp_no' => '',
                'tanggal_bergabung' => Carbon::now(),
                'status_anggota' => true,
                'password' => Hash::make('123456'),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            //PiMi 1
            [
                'roleID' => 4, 
                'username' => 'Ratna01',
                'nama' => 'Ratna',
                'DoB' => '1967-02-17',
                'TelpNo' => '7863453',
                'ortu_nama' => '',
                'ortu_telp_no' => '',
                'tanggal_bergabung' => Carbon::now(),
                'status_anggota' => true,
                'password' => Hash::make('123456'),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            //PiMi 2
            [
                'roleID' => 4, 
                'username' => 'Budi01',
                'nama' => 'Budi',
                'DoB' => '1967-02-17',
                'TelpNo' => '7863453',
                'ortu_nama' => '',
                'ortu_telp_no' => '',
                'tanggal_bergabung' => Carbon::now(),
                'status_anggota' => true,
                'password' => Hash::make('123456'),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            //PiMi 2
            [
                'roleID' => 4, 
                'username' => 'Ika01',
                'nama' => 'Ika',
                'DoB' => '1967-02-17',
                'TelpNo' => '7863453',
                'ortu_nama' => '',
                'ortu_telp_no' => '',
                'tanggal_bergabung' => Carbon::now(),
                'status_anggota' => true,
                'password' => Hash::make('123456'),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // anggota
            [
            'roleID' => 2,
            'username' => 'Yosef_W',
            'nama' => 'Yosefus Wahyu Wibowo',
            'DoB' => '2007-02-17',
            'TelpNo' => '8636374',
            'ortu_nama' => 'Antonius Wibowo',
            'ortu_telp_no' => '7826346',
            'tanggal_bergabung' => Carbon::now(),
            'status_anggota' => true,
            'password' => Hash::make('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            ],
            [
            'roleID' => 2,
            'username' => 'Chris_S',
            'nama' => 'Christophorus Samuel Setiawan',
            'DoB' => '2006-05-23',
            'TelpNo' => '8567234',
            'ortu_nama' => 'Gregorius Setiawan',
            'ortu_telp_no' => '7845123',
            'tanggal_bergabung' => Carbon::now(),
            'status_anggota' => true,
            'password' => Hash::make('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            ],
            [
            'roleID' => 2,
            'username' => 'Matt_P',
            'nama' => 'Matheus Putra Widodo',
            'DoB' => '2005-08-12',
            'TelpNo' => '8234567',
            'ortu_nama' => 'Paulus Widodo',
            'ortu_telp_no' => '7891234',
            'tanggal_bergabung' => Carbon::now(),
            'status_anggota' => true,
            'password' => Hash::make('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            ],
            [
            'roleID' => 2,
            'username' => 'Dom_L',
            'nama' => 'Dominikus Lukas Santoso',
            'DoB' => '2006-11-30',
            'TelpNo' => '8345612',
            'ortu_nama' => 'Fransiskus Santoso',
            'ortu_telp_no' => '7234561',
            'tanggal_bergabung' => Carbon::now(),
            'status_anggota' => true,
            'password' => Hash::make('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            ],
            [
            'roleID' => 2,
            'username' => 'Pet_T',
            'nama' => 'Petrus Thomas Gunawan',
            'DoB' => '2007-04-15',
            'TelpNo' => '8456723',
            'ortu_nama' => 'Benediktus Gunawan',
            'ortu_telp_no' => '7345612',
            'tanggal_bergabung' => Carbon::now(),
            'status_anggota' => true,
            'password' => Hash::make('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            ],
            [
            'roleID' => 2,
            'username' => 'Mike_S',
            'nama' => 'Mikael Sebastian Tanaka',
            'DoB' => '2008-01-25',
            'TelpNo' => '8567234',
            'ortu_nama' => 'Yohanes Tanaka',
            'ortu_telp_no' => '7456123',
            'tanggal_bergabung' => Carbon::now(),
            'status_anggota' => true,
            'password' => Hash::make('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            ],
            [
            'roleID' => 2,
            'username' => 'Gab_W',
            'nama' => 'Gabriel William Susanto',
            'DoB' => '2006-07-18',
            'TelpNo' => '8678345',
            'ortu_nama' => 'Stefanus Susanto',
            'ortu_telp_no' => '7567234',
            'tanggal_bergabung' => Carbon::now(),
            'status_anggota' => true,
            'password' => Hash::make('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            ],
            [
            'roleID' => 2,
            'username' => 'Raf_K',
            'nama' => 'Rafael Kevin Hartanto',
            'DoB' => '2007-03-28',
            'TelpNo' => '8789456',
            'ortu_nama' => 'Markus Hartanto',
            'ortu_telp_no' => '7678345',
            'tanggal_bergabung' => Carbon::now(),
            'status_anggota' => true,
            'password' => Hash::make('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            ],
            [
            'roleID' => 2,
            'username' => 'Aug_D',
            'nama' => 'Agustinus Daniel Wijaya',
            'DoB' => '2005-09-05',
            'TelpNo' => '8890567',
            'ortu_nama' => 'Vincentius Wijaya',
            'ortu_telp_no' => '7789456',
            'tanggal_bergabung' => Carbon::now(),
            'status_anggota' => true,
            'password' => Hash::make('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            ],
            [
            'roleID' => 2,
            'username' => 'Ben_F',
            'nama' => 'Benediktus Felix Tanuwijaya',
            'DoB' => '2006-12-22',
            'TelpNo' => '8901678',
            'ortu_nama' => 'Lukas Tanuwijaya',
            'ortu_telp_no' => '7890567',
            'tanggal_bergabung' => Carbon::now(),
            'status_anggota' => true,
            'password' => Hash::make('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            ],
            [
            'roleID' => 2,
            'username' => 'Val_R',
            'nama' => 'Valentinus Ryan Sugiarto',
            'DoB' => '2008-06-14',
            'TelpNo' => '8912789',
            'ortu_nama' => 'Dominikus Sugiarto',
            'ortu_telp_no' => '7901678',
            'tanggal_bergabung' => Carbon::now(),
            'status_anggota' => true,
            'password' => Hash::make('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            ],
            [
            'roleID' => 2,
            'username' => 'Nic_A',
            'nama' => 'Nicholas Adrian Kusuma',
            'DoB' => '2007-10-08',
            'TelpNo' => '8923890',
            'ortu_nama' => 'Andreas Kusuma',
            'ortu_telp_no' => '7912789',
            'tanggal_bergabung' => Carbon::now(),
            'status_anggota' => true,
            'password' => Hash::make('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            ],
            [
            'roleID' => 2,
            'username' => 'Theo_J',
            'nama' => 'Theodorus Jason Pranoto',
            'DoB' => '2006-03-19',
            'TelpNo' => '8934901',
            'ortu_nama' => 'Robertus Pranoto',
            'ortu_telp_no' => '7923890',
            'tanggal_bergabung' => Carbon::now(),
            'status_anggota' => true,
            'password' => Hash::make('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            ],
            [
            'roleID' => 2,
            'username' => 'Alex_M',
            'nama' => 'Alexander Martin Halim',
            'DoB' => '2005-07-27',
            'TelpNo' => '8945012',
            'ortu_nama' => 'Cornelius Halim',
            'ortu_telp_no' => '7934901',
            'tanggal_bergabung' => Carbon::now(),
            'status_anggota' => true,
            'password' => Hash::make('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            ],
            [
            'roleID' => 2,
            'username' => 'Vin_L',
            'nama' => 'Vincentius Louis Tanjung',
            'DoB' => '2008-09-03',
            'TelpNo' => '8956123',
            'ortu_nama' => 'Ignatius Tanjung',
            'ortu_telp_no' => '7945012',
            'tanggal_bergabung' => Carbon::now(),
            'status_anggota' => true,
            'password' => Hash::make('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            ],
            [
            'roleID' => 2,
            'username' => 'Leo_P',
            'nama' => 'Leonardo Patrick Salim',
            'DoB' => '2007-12-11',
            'TelpNo' => '8967234',
            'ortu_nama' => 'Timotius Salim',
            'ortu_telp_no' => '7956123',
            'tanggal_bergabung' => Carbon::now(),
            'status_anggota' => true,
            'password' => Hash::make('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            ],
            [
            'roleID' => 2,
            'username' => 'Stan_R',
            'nama' => 'Stanislaus Raymond Tiono',
            'DoB' => '2006-01-30',
            'TelpNo' => '8978345',
            'ortu_nama' => 'Kristoforus Tiono',
            'ortu_telp_no' => '7967234',
            'tanggal_bergabung' => Carbon::now(),
            'status_anggota' => true,
            'password' => Hash::make('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            ],
            [
            'roleID' => 2,
            'username' => 'Phil_A',
            'nama' => 'Philipus Anthony Wibisono',
            'DoB' => '2008-04-25',
            'TelpNo' => '8989456',
            'ortu_nama' => 'Bernardus Wibisono',
            'ortu_telp_no' => '7978345',
            'tanggal_bergabung' => Carbon::now(),
            'status_anggota' => true,
            'password' => Hash::make('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            ],
            [
            'roleID' => 2,
            'username' => 'Tim_N',
            'nama' => 'Timotius Nathan Santosa',
            'DoB' => '2007-08-16',
            'TelpNo' => '8990567',
            'ortu_nama' => 'Maximus Santosa',
            'ortu_telp_no' => '7989456',
            'tanggal_bergabung' => Carbon::now(),
            'status_anggota' => true,
            'password' => Hash::make('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            ],
            [
            'roleID' => 2,
            'username' => 'Mar_F',
            'nama' => 'Markus Ferdinand Winata',
            'DoB' => '2005-11-20',
            'TelpNo' => '8901678',
            'ortu_nama' => 'Gregorius Winata',
            'ortu_telp_no' => '7990567',
            'tanggal_bergabung' => Carbon::now(),
            'status_anggota' => true,
            'password' => Hash::make('123456'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            ]
        ];
        DB::table('anggota')->insert($anggotas);
    }
}